name: Build & Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io
  NOMAD_VERSION: "1.2.2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.13"

      - run: mix deps.get
      - run: mix deps.compile --force
      - run: mix compile --force --warnings-as-errors
      - run: mix test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          # Lowercases GITHUB_REGISTRY, docker build breaks with tags that contain uppercase letters
          echo "IMAGE_ID=${IMAGE_REGISTRY}/${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{env.IMAGE_ID}}:latest,${{env.IMAGE_ID}}:${{ github.sha }}"
          cache-from: type=registry,ref=${{env.IMAGE_ID}}:latest
          cache-to: type=inline

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        shell: bash
    env:
      NOMAD_CACERT: "/tmp/ca.pem"
      NOMAD_CLIENT_CERT: "/tmp/client.pem"
      NOMAD_CLIENT_KEY: "/tmp/client-key.pem"

    steps:
      - name: Set environment variables
        run: |
          # Lowercases GITHUB_REGISTRY, docker build breaks with tags that contain uppercase letters
          echo "IMAGE_ID=${IMAGE_REGISTRY}/${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: ${{ secrets.WG_ENDPOINT }}
          endpoint_public_key: ${{ secrets.WG_ENDPOINT_PUBLIC_KEY }}
          ips: ${{ secrets.WG_IPS }}
          allowed_ips: ${{ secrets.WG_ALLOWED_IPS }}
          private_key: ${{ secrets.WG_PRIVATE_KEY }}

      -
        name: Add WG route
        run: |
          ifname=$(ls /sys/class/net/ | grep '^wg')
          sudo ip route add ${{ secrets.WG_ALLOWED_IPS }} dev $ifname

      -
        name: Download Nomad
        run: |
          cd /usr/local/bin && \
          wget --quiet "https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip" && \
          unzip "nomad_${NOMAD_VERSION}_linux_amd64.zip" && \
          chmod +x nomad

      -
        name: Populate cert files
        run: |
          echo "$SECRET_NOMAD_CA_CERT" >> "$NOMAD_CACERT" && \
          echo "$SECRET_NOMAD_CLIENT_CERT" >> "$NOMAD_CLIENT_CERT" && \
          echo "$SECRET_NOMAD_CLIENT_KEY" >> "$NOMAD_CLIENT_KEY"
        env:
          SECRET_NOMAD_CA_CERT: ${{ secrets.NOMAD_CA_CERT }}
          SECRET_NOMAD_CLIENT_CERT: ${{ secrets.NOMAD_CLIENT_CERT }}
          SECRET_NOMAD_CLIENT_KEY: ${{ secrets.NOMAD_CLIENT_KEY }}

      # - name: Debugging with ssh
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     limit-access-to-users:  ${{ env.GITHUB_REPOSITORY_OWNER }}

      -
        name: Deploy Nomad job
        run: |
          run_output=$(nomad job run -verbose -var "image_version=${{ github.sha }}" -var "ghcr_password=$GHCR_PASSWORD" -var "image_id=$IMAGE_ID" -detach f1bot.nomad)
          ./scripts/check-nomad-deployment.sh "$run_output"
        env:
          NOMAD_TOKEN: "${{ secrets.NOMAD_TOKEN }}"
          NOMAD_ADDR: "${{ secrets.NOMAD_URL }}"
          NOMAD_TLS_SERVER_NAME: "server.global.nomad"
          GHCR_PASSWORD: "${{ secrets.GHCR_PASSWORD }}"

      -
        name: Shred credentials
        if: always()
        run: |
          echo -e "[BEFORE SHREDDING]\n\n"
          ls -lh "$NOMAD_CACERT" "$NOMAD_CLIENT_CERT" "$NOMAD_CLIENT_KEY"

          echo -e "\n[SHREDDING]"
          shred "$NOMAD_CACERT"
          shred "$NOMAD_CLIENT_CERT"
          shred "$NOMAD_CLIENT_KEY"

          echo -e "\n[AFTER SHREDDING]\n\n"
          ls -lh "$NOMAD_CACERT" "$NOMAD_CLIENT_CERT" "$NOMAD_CLIENT_KEY"
